server = 'http://109.86.92.50:80'
p1 = 'cc={}'
p2 = 'cc={0}&pin={1}'
t = 'tries={}'
add = 'cc={0}&bal={1}'
withdraw = 'cc={0}&bal=-{1}'
block = 'block={}'
gname = 'gname={}'
chpin = 'cc={0}&pin={1}&npin={2}'
transaction = 'from={0}&to={1}&bal={2}'
s_t = 'Your transaction to {0} is successful!\nBalance before: {1}\nCurrent balance: {2}\nTransaction time: {3}'
